"""Remove redundant fullname from users

Revision ID: 3a7f559fa342
Revises: 10122d14f655
Create Date: 2025-12-12 14:11:07.079222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a7f559fa342"
down_revision: Union[str, Sequence[str], None] = "10122d14f655"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
