"""Refactoring securities models

Revision ID: 8cd45dd2636e
Revises: a799a39e033b
Create Date: 2025-12-12 17:53:36.331968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8cd45dd2636e'
down_revision: Union[str, Sequence[str], None] = 'a799a39e033b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('security_type', sa.Enum('COMMON_STOCK', 'PREFERRED_STOCK', 'BOND', 'ETF', 'MUTUAL_FUND', 'OPTION', 'FUTURE', 'CRYPTOCURRENCY', 'ADR', name='securitytype'), nullable=True),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_symbol'), ['symbol'], unique=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_id', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(None, 'security', ['security_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('security_id')

    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_symbol'))

    op.drop_table('security')
    # ### end Alembic commands ###
