"""Refactoring transactions models

Revision ID: a799a39e033b
Revises: ff34a597c317
Create Date: 2025-12-12 17:46:53.905964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a799a39e033b'
down_revision: Union[str, Sequence[str], None] = 'ff34a597c317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP_LOSS', 'STOP_LIMIT', name='transactionordertype'), nullable=True))
        batch_op.add_column(sa.Column('options_contract', sa.Enum('CALL', 'PUT', 'NONE', name='transactionoptionscontract'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('options_contract')
        batch_op.drop_column('order_type')

    # ### end Alembic commands ###
